apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness 
  name: readiness
spec:
  restartPolicy: OnFailure
  containers:
  - name: readiness 
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 40; rm -rf /tmp/healthy; sleep 900
    readinessProbe: 
      exec:
        command: ["test","-e","/tmp/healthy"]
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
